[general]
import = ["~/.config/alacritty/os.toml"]

[font]
size = 14.0

[font.normal]
family = "BlexMono Nerd Font"
style = "Regular"

[font.bold]
family = "BlexMono Nerd Font"
style = "Bold"

[font.italic]
family = "BlexMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "BlexMono Nerd Font"
style = "Bold Italic"

[window]
opacity = 0.97
padding = { x = 12, y = 12 }
dynamic_padding = true

[cursor]
style = { shape = "Beam", blinking = "On" }
unfocused_hollow = true

# Nordfox (nightfox.nvim)
[colors.primary]
background = "#2e3440"
foreground = "#cdcecf"
dim_foreground = "#aeb3bb"
bright_foreground = "#e5e9f0"

[colors.cursor]
text = "#2e3440"
cursor = "#cdcecf"

[colors.vi_mode_cursor]
text = "#2e3440"
cursor = "#88c0d0"

[colors.search.matches]
foreground = "#2e3440"
background = "#88c0d0"

[colors.search.focused_match]
foreground = "#2e3440"
background = "#a3be8c"

[colors.footer_bar]
foreground = "#cdcecf"
background = "#3b4252"

[colors.hints.start]
foreground = "#2e3440"
background = "#ebcb8b"

[colors.hints.end]
foreground = "#2e3440"
background = "#81a1c1"

[colors.selection]
text = "#cdcecf"
background = "#3e4a5b"

[colors.normal]
black   = "#3b4252"
red     = "#bf616a"
green   = "#a3be8c"
yellow  = "#ebcb8b"
blue    = "#81a1c1"
magenta = "#b48ead"
cyan    = "#88c0d0"
white   = "#e5e9f0"

[colors.bright]
black   = "#465780"
red     = "#d06f79"
green   = "#b1d196"
yellow  = "#f0d399"
blue    = "#8cafd2"
magenta = "#c895bf"
cyan    = "#93ccdc"
white   = "#e7ecf4"

[colors.dim]
black   = "#2e3440"
red     = "#a54e56"
green   = "#89aa6c"
yellow  = "#d6b271"
blue    = "#6f8aa6"
magenta = "#9d7495"
cyan    = "#74a7bb"
white   = "#aeb3bb"
