# Auto-generated by omarchy-theme-set-templates from the active Omarchy
# theme's colors.toml. Don't edit the rendered file directly — edit this
# template in dotfiles/omarchy/themed/spotify-player.toml.tpl.
#
# spotify-player loads theme.toml at startup; switch themes with `T` inside
# the app, or restart spotify-player to pick up changes after omarchy-theme-set.

[[themes]]
name = "omarchy"
[themes.palette]
background = "{{ background }}"
foreground = "{{ foreground }}"
black = "{{ color0 }}"
red = "{{ color1 }}"
green = "{{ color2 }}"
yellow = "{{ color3 }}"
blue = "{{ color4 }}"
magenta = "{{ color5 }}"
cyan = "{{ color6 }}"
white = "{{ color7 }}"
bright_black = "{{ color8 }}"
bright_red = "{{ color9 }}"
bright_green = "{{ color10 }}"
bright_yellow = "{{ color11 }}"
bright_blue = "{{ color12 }}"
bright_magenta = "{{ color13 }}"
bright_cyan = "{{ color14 }}"
bright_white = "{{ color15 }}"
